export const ACTIONS = {
	GET_TEXT: 'GET_TEXT',
	SET_TEXT: 'SET_TEXT',
	GET_IMAGE: 'GET_IMAGE',
	SET_IMAGE: 'SET_IMAGE',
	GET_SELECTION: 'GET_SELECTION',
	SET_SELECTION: 'SET_SELECTION',
	GET_MODE: 'GET_MODE',
	SET_MODE: 'SET_MODE',
	GET_SETTINGS: 'GET_SETTINGS',
	SET_SETTINGS: 'SET_SETTINGS',
	SET_STATUS: 'SET_STATUS',
	GET_STATUS: 'GET_STATUS',
};
